### ISSUE TITLE
找不到签到任务

### ISSUE THREAD

**Issue by TheLaulee** [JasonYANG170/AutoCheckBJMF#1]
自己建了一个班级试，显示找不到签到任务。。。
![LIF D%5(PX2VTITD0{ _~9W](https://github.com/JasonYANG170/AutoCheckBJMF/assets/61400239/048f46d9-2999-49d1-8850-6ea9265ff4a5)

**Comment by JasonYANG170** [comment]
确认你的班级号是99351，另外你可以尝试在其他浏览器登录或者清除当前浏览器Cookie以便重新获取新的Cookie（我更建议通过抓包软件获取微信内的Cookie）

**Comment by TheLaulee** [comment]
好了好了抓包用微信里的cookie就可以了，换了个谷歌浏览器也不行

**Comment by Danny8yo** [comment]
作者大大你好，请问你们这个签到可以在游览器里面进行吗，我们这边浏览器登陆签到会提示“请在微信中进行”

**Comment by JasonYANG170** [comment]
> 作者大大你好，请问你们这个签到可以在游览器里面进行吗，我们这边浏览器登陆签到会提示“请在微信中进行”

如果有此情况，需要使用抓包软件（Fiddler,HttpCanary,抓包精灵）从微信抓取Cookie

**Comment by Danny8yo** [comment]
> > 作者大大你好，请问你们这个签到可以在游览器里面进行吗，我们这边浏览器登陆签到会提示“请在微信中进行”
> 
> 如果有此情况，需要使用抓包软件（Fiddler,HttpCanary,抓包精灵）从微信抓取Cookie
解决了，谢谢

**Comment by Danny8yo** [comment]
> > 作者大大你好，请问你们这个签到可以在游览器里面进行吗，我们这边浏览器登陆签到会提示“请在微信中进行”
> 
> 如果有此情况，需要使用抓包软件（Fiddler,HttpCanary,抓包精灵）从微信抓取Cookie

解决了，谢谢

**Comment by Dec10969** [comment]
尝试了一下，能签到成功，但是位置误差有二十多公里，想知道解决方法qwq

**Comment by JasonYANG170** [comment]
> 尝试了一下，能签到成功，但是位置误差有二十多公里，想知道解决方法qwq
> 

请修改经纬度坐标，可以使用手机指南针中的坐标或者百度找可以显示坐标的地图网站

**Comment by JasonYANG170** [comment]
> 尝试了一下，能签到成功，但是位置误差有二十多公里，想知道解决方法qwq
> 

其实通常来说，老师只会检查是否签到成功，因为不在范围内的是无法签到的。而本程序可以越过范围检查。如果有详细要求，可以自行修改经纬度

**Comment by Dec10969** [comment]
> > 尝试一下，能签到成功，但是位置坐标有二十多公里，想知道解决方法qwq
> 
> 请修改经纬度坐标，可以使用手机指南针中的坐标或者百度找可以显示坐标的地图网站

嗯嗯了解，我手机上经纬是准确的，但是签到界面误差很多，想知道你调试的时候也是准确的吗？老师会看所以还是想尽量解决qwq

**Comment by JasonYANG170** [comment]
> > > 尝试一下，能签到成功，但是位置坐标有二十多公里，想知道解决方法qwq
> > 
> > 
> > 请修改经纬度坐标，可以使用手机指南针中的坐标或者百度找可以显示坐标的地图网站
> 
> 嗯嗯了解，我手机上经纬是准确的，但是签到界面误差很多，想知道你调试的时候也是准确的吗？老师会看所以还是想尽量解决qwq

是的，我在测试时正常，您可以尝试使用腾讯坐标拾取API：https://lbs.qq.com/getPoint/

**Comment by Dec10969** [comment]
hhhh还是我来问问题了
插件一开机使用不了 要后面用一段时间电脑才行 不知道为什么
开机的时候用窗体会闪退（我想办法把这段报错截了下来
![Uploading 微信图片_20240414094034.jpg…]()

**Comment by Dec10969** [comment]
hhhh还是我来问问题了
插件一开机使用不了 要后面用一段时间电脑才行 不知道为什么
开机的时候用窗体会闪退（我想办法把这段报错截了下来
![微信图片_20240414094034](https://github.com/JasonYANG170/AutoCheckBJMF/assets/161946118/f15000b9-e0e3-4bd9-9da5-ff255349e548)

**Comment by JasonYANG170** [comment]
> hhhh还是我来问问题了
> 插件一开机使用不了 要后面用一段时间电脑才行 不知道为什么
> 开机的时候用窗体会闪退（我想办法把这段报错截了下来
> ![微信图片_20240414094034](https://github.com/JasonYANG170/AutoCheckBJMF/assets/161946118/f15000b9-e0e3-4bd9-9da5-ff255349e548)
> 

时间格式是00:00，定时修改为设置为09:38即可
