### ISSUE TITLE
不是问题，是一个讨论：添加 json 文本来代替输入

### ISSUE THREAD

**Issue by Halogly** [JasonYANG170/AutoCheckBJMF#2]
我为了方便使用，并且每次输入都挺麻烦的，所以我改了下代码，变成引用json里面的数值，这样只需要修改json里面的数据就行，而不需要每次打开都要输入一遍

**Comment by JasonYANG170** [comment]
这是个不错的想法，非常感谢，我会在后续加入，你也可以提交PR合并

**Comment by Halogly** [comment]
[自动打卡 - 副本.zip](https://github.com/JasonYANG170/AutoCheckBJMF/files/14811388/-.zip)
这个是我修改过的，根据使用习惯修改的

**Comment by JasonYANG170** [comment]
非常感谢，已发布4.0版本，增加了json引用和定时开启功能，源码已更新
