### ISSUE TITLE
你好，请问能否支持拍照+定位签到的模式呢？

### ISSUE THREAD

**Issue by weandy** [JasonYANG170/AutoCheckBJMF#4]
你好，请问能否支持拍照+定位签到的模式呢？我记得之前看过一次数据包，也是夹杂了定位，然后上传图片的一个链接还是什么，忘记了，回头我会补充一下请求文本

**Comment by JasonYANG170** [comment]
支持扫码签到+定位签到，班级魔方好像没有上传图片拍照签到的模式🧐

**Comment by weandy** [comment]
> 支持扫码签到+定位签到，班级魔方好像没有上传图片拍照签到的模式🧐


抱歉刚刚回复，我这边有这种模式，应该是我们学校开启了，我已经找到了解决办法，直接改请求时候的参数就行了，POST文本中的内容不用改就行了，
POST /student/punchs/course/XXXXX/XXXXX HTTP/1.1
Host: XXX.XXX.cn
Connection: keep-alive
Content-Length: 350
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Origin: https://XXX.XXX.cn
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 XXXXXX WeChat/arm64 Weixin NetType/5G Language/zh_CN ABI/arm64
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/wxpic,image/tpg,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
X-Requested-With: com.tencent.mm
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: https://XXXX.XXXX.cn/student/punchs/course/XXXX/2322XXXX140
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en-CN;q=0.8,en-US;q=0.7,en;q=0.6
Cookie: remember_studentXXXXXXXX

lat=35.XXXX&lng=114.XXXX&acc=3.897678852081299&res=XXXXXXXXXXXXXXXXX
就是我还没看懂这个res是什么，奇怪得嘞，不过直接改掉请求头，之前如果你上传过服务器照片，套用这个res就行，没问题的，我试过

**Comment by JasonYANG170** [comment]
感谢提出，我稍后研究一下🧐

**Comment by lemon1900s** [comment]
请问怎么用才能过拍照打卡

**Comment by lemon1900s** [comment]
呼叫温迪用户在吗

**Comment by weandy** [comment]
> 呼叫温迪用户在吗

在的哦，我是发现你直接post那个链接，下面的body内容抓包一次含有图片的内容，正常提交一次看看数据包，以后直接用这个应该就可以了，拍照打卡本质上还是GPS，其实就是加了个参数而已

**Comment by JasonYANG170** [comment]
感谢帮助，已发布V6.0版本，支持GPS+签到拍照模式

**Comment by JasonYANG170** [comment]
res的值应该是通过加密处理过并且格式为%5B%22+图像加密名称+%22%5D，前缀和后缀应该是判别符号，在V6.0版本中我选取了一张黑色图片并去除了图像加密名称的后缀与一个加密字符，测试发现**可以成功签到**，**并且该图片无法查看**，

**注意：**_如果您对传入的照片有严格要求，请自行抓包由您上传的图片的res值修改data.json中res的值(我注意到班级魔方提示图片只能保存3天，也就是3天后依旧使用旧res值则上传的图片无法查看)_

**Comment by weandy** [comment]
> res的值应该是通过加密处理过并且格式为%5B%22+图像加密名称+%22%5D，前缀和后缀应该是判别符号，在V6.0版本中我选取了一张黑色图片并去除了图像加密名称的后缀与一个加密字符，测试发现**可以成功签到**，**并且该图片无法查看**，
> 
> **注意：**_如果您对传入的照片有严格要求，请自行抓包由您上传的图片的res值修改data.json中res的值(我注意到班级魔方提示图片只能保存3天，也就是3天后依旧使用旧res值则上传的图片无法查看)_

好牛逼老哥，点赞！

**Comment by lemon1900s** [comment]
我刚知道GitHub这个网站请问怎么使用直接下载zip吗自己电脑需要安装python吗大佬可否教学一下

**Comment by lemon1900s** [comment]
@weandy

**Comment by lemon1900s** [comment]
我输入cookie后直接闪退了

**Comment by JasonYANG170** [comment]
> 我输入cookie后直接闪退了

https://github.com/JasonYANG170/AutoCheckBJMF/releases/tag/V6.0如果您是windows电脑，建议您下载msi安装包，通常来说python环境已经打包，不需要单独下载，如果输入Cookie闪退，请确定您输入的Cookie正确

**Comment by lemon1900s** [comment]
@JasonYANG170 我下载好了
![设置](https://github.com/JasonYANG170/AutoCheckBJMF/assets/167997737/e0766fe0-5ed9-4d3a-a445-0692846121f0)
zh这样就是设置好了吗 GPS 加拍照就可以了是不是

**Comment by lemon1900s** [comment]
@JasonYANG170 保持微信登陆和打开你的程序就行是吧 我没接触过这个感谢大佬不吝赐教好人平安

**Comment by lemon1900s** [comment]
@JasonYANG170 我已经验证过了可以用感谢大佬牛牛牛

**Comment by JasonYANG170** [comment]
> @JasonYANG170 我已经验证过了可以用感谢大佬牛牛牛

☺️好的，遇到问题请向我提出

**Comment by Daidaiju** [comment]
您好 请问能否发一个更详细一点的教程呢 拍照+GPS定位打卡
@weandy @JasonYANG170

**Comment by Daidaiju** [comment]
@lemon1900s 您好 想请问一下具体拍照定位签到该如何操作 能不能教学一下 没接触过这个
