### ISSUE TITLE
程序运行后只能自动签到第一次检测到的签到，第二个签到没有检测到，也没有自动签到

### ISSUE THREAD

**Issue by Moeus** [JasonYANG170/AutoCheckBJMF#5]

**Comment by JasonYANG170** [comment]
是的，这是班级魔方的机制，只能在第一次签到完成后Cookie值会变更，**需要重新抓包**获取新的Cookie才可完成第二次签到。由于Cookie需要在微信内完成，暂时无法通过自动化完成，只能手动抓取。

**Comment by JasonYANG170** [comment]
我在发布最初版本时是建议使用网页版，但是有的反馈说无法获取签到，所以改成从微信抓取成功率高

你是在网页版选择百度账户登录吗？可以连续签到吗？我有想过绑定百度账户选择百度账户登录可能可以提高Cookie有效期，具体我还没有测试

**Comment by Moeus** [comment]
> 我在发布最初版本时是建议使用网页版，但是有的反馈说无法获取签到，所以改成从微信抓取成功率高
> 
> 你是在网页版选择百度账户登录吗？可以连续签到吗？我有想过绑定百度账户选择百度账户登录可能可以提高Cookie有效期，具体我还没有测试

    就是直接登录那个网页版的班级魔方，微信扫码登录，网址是k8n.cn，然后点“学生中心”微信扫码登录，登录成功之后用edge浏览器扩展插件“cookie-editor”导出cookie
    
    导出的cookie直接填入你的那个程序，是可以签到的，刚刚试了成功了一次。
    还不能确定是不是能连续签到，我明天早上早自习加两节课，试验一下看看。但是在edge浏览器打开设置页面里查看到的这个班级魔方网页的cookie到期时间是挺长的，所以我猜测这个是可以连续签到的，具体看看明天

**Comment by JasonYANG170** [comment]
你可以尝试连续两次进入签到界面并查看Cookie值，如果在浏览器中第二次抓取未变更，应该是可以进行连续签到（从微信第二次抓取会变更）

**Comment by Moeus** [comment]
大佬大佬，重大发现，
         在此之前，先说明一下，cookie是有多个字段的，每个字段后面有值，用来记录用户的信息，在此基础上，我有了以下发现
         昨天跟你说的网页版的cookie，我有一个发现，先看图一，我里面是我从网页获取的cookie，这些cookie都是两个字段，字段名我圈出来了，然后你看前面一个名为“s”的字段，“=”等号后面他的值是有变化的，但是另一个字段，他的值是不变的，我获取那么多次cookie，他都没有变化。
         然后刚才，我就想着能不能只用第二个字段作为cookie去进行签到，然后，居然成功了，
         这证明仅用第二字段去填入程序进行操作是可行的，并且，因为第二个字段是不变的，在浏览器cookie管理里面看到的第二个字段的过期时间是明年，所以说，**使用cookie中的第二个字段来输入程序是可能可以实现连续签到的** 
![89b453f1784d5801d9f3685685bb8ce](https://github.com/JasonYANG170/AutoCheckBJMF/assets/81859321/abc6943d-3d7f-4cf4-ba72-f4de60d59e81)
![960e840261a4ba5345e5c35c5ad5074](https://github.com/JasonYANG170/AutoCheckBJMF/assets/81859321/522fc19c-774d-4397-b8c7-ced746250e60)

**Comment by JasonYANG170** [comment]
非常感谢，您的方法我在测试中有效。现已发布V5.2版本加入连续签到功能，同时您无需手动删除无效字符，程序会自动截取有效值运行，支持从微信、浏览器获取的Cookie值

**Comment by Moeus** [comment]
> 非常感谢，您的方法我在测试中有效。现已发布V5.2版本加入连续签到功能，同时您无需手动删除无效字符，程序会自动截取有效值运行，支持从微信、浏览器获取的Cookie值

能帮上忙我很高兴😄
