### ISSUE TITLE
填完检索间隔就退出了

### ISSUE THREAD

**Issue by 1shuqing** [JasonYANG170/AutoCheckBJMF#6]
时间检索填的120

**Comment by JasonYANG170** [comment]
检索间隔过后是程序向data.json写入数据的步骤，如果出现闪退可能是安装路径位于C盘，需要管理员权限才可写入，请**右键程序以管理员权限运行**

**Comment by 1shuqing** [comment]
成功了，感谢大佬

**Comment by 1shuqing** [comment]
如何更改已填写数据？我完整输入完毕一次后关闭程序再重新打开就改不了班级id之类的了，而json文件改写保存时说我没有权限改不了

**Comment by JasonYANG170** [comment]
> 如何更改已填写数据？我完整输入完毕一次后关闭程序再重新打开就改不了班级id之类的了，而json文件改写保存时说我没有权限改不了

您可以先将json文件移动到桌面，在桌面修改并保存后在移回原位置替换即可😊

**Comment by 1shuqing** [comment]
解决了，再次感谢👍
