### ISSUE TITLE
魔方产品系列签到

### ISSUE THREAD

**Issue by MF-142** [JasonYANG170/AutoCheckBJMF#7]
你好，注意到本程序是按照班级魔方“k8n.cn”网址开发的。现在又多出来衍生产品，这些东西基本代码都是一样的，网址指向不同而已。

例如：
学工魔方：
`xgmf.g8n.cn`
校园魔方：
`xymf.k8n.cn`
学工助手：
`xgzs.g8n.cn`

请问能否将以上产品列入匹配呢！感谢！！！

**Comment by JasonYANG170** [comment]
收到了您的邮件，我会在近期研究这个产品
