### ISSUE TITLE
源码zip包报毒

### ISSUE THREAD

**Issue by jrh8182** [JasonYANG170/AutoCheckBJMF#8]
想在linux上使用，尝试下载最后一版源码zip包时，Windows defender报特洛伊木马Trojan:Script/Wacatac.H!ml
同时chrome缓存文件也报毒，不太敢用了。
缓存文件上传virustotal也确实红了几个。
请问是误报还是被投毒了～

**Comment by jrh8182** [comment]
![从GitHub上下载班级魔法打卡报毒情况](https://github.com/user-attachments/assets/de6784f4-d2ff-4e53-be57-f757f4d38948)
![从GitHub上下载班级魔法打卡报毒情况3](https://github.com/user-attachments/assets/0441d1a2-2886-4424-a788-4c896c5d290a)
virustotal 检测
https://www.virustotal.com/gui/file/84b2cafd81cf80cd12d86ae60a5c6e9bf23242cbd3feb7cfa63477a584f2934d/detection

**Comment by JasonYANG170** [comment]
应该不会，源码是PyCharm，源码包是github封装的，程序打包使用的Pyinstaller,也不会有啥问题，如果担心的话可以自行创建个Py文件，把源码复制进去。

**Comment by JasonYANG170** [comment]
我已经毕业了，没有在维护这个项目，过几天重新再重新封装看一下

**Comment by jrh8182** [comment]
> 应该不会，源码是PyCharm，源码包是github封装的，程序打包使用的Pyinstaller,也不会有啥问题，如果担心的话可以自行创建个Py文件，把源码复制进去。

好的，那可能是误报了，感谢！
